# Dataset paths and parameters
seed: 
  seed_value: 42  

data:
  csv_data_file: "../../../data/processed.csv"  
  csv_test_idx: "../../../data/test_idx.csv"
  csv_train_idx: "../../../data/train_idx.csv"
  cif_directory: "../../../../data/np_cifs"
  ionic_conductivity_column: "Ionic conductivity (S cm-1)"  

# Graph settings
graph:
  cutoff: 5.0
  threebody_cutoff: 5.0
  include_line_graph: True  
  
# Dataset splitting (for cross-validation)
split:
  k_folds: 5      
  shuffle: True      
  random_state: 42   
  train_shuffle: True
  val_shuffle: False
  test_shuffle: False
  num_workers: 0 
 
# Model parameters for M3GNet
m3gnet:
  is_intensive: [True]
  readout_type: ["set2set"]
  nblocks: [3]
  dim_node_embedding: [128]
  dim_edge_embedding: [128]
  units: [64]
  threebody_cutoff: [5.0]
  cutoff: [5.0]

# Model parameters for SO3Net
so3net:
  is_intensive: [True]
  target_property: ["graph"]
  readout_type: ["set2set"]
  nmax: [2]
  lmax: [1]
  nblocks: [3]
  dim_node_embedding: [64]
  units: [32]
  cutoff: [5.0]
  nlayers_readout: [3]

# Hyperparameter 
hyperparameters:
  num_cases: 1
  weight_decay: 0 
  batch_size: [35] 
  lr: [0.001]       
  max_epochs: [80]  

# Training parameters
training:
  accelerator: "gpu"  

# Logger settings
logger:
  save_dir: "logs"       
  name: "Model_training" 

# Plot settings
plot:
  fig_size: [10, 6]   
  dpi: 300            

# Output settings
output:
  raw_data_dir_train: "./dgl_train"   
  raw_data_dir_test: "./dgl_test"     
  finetuned_model_dir: "./finetuned_model"

# Pretraining
pretraining:
  use_pretrained: true
  model_name: "M3GNet-MP-2018.6.1-Eform" 